# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

def import_pods
   pod 'Parse'
end

target 'OUAS' do
    import_pods
end

target 'OUASTests' do
    import_pods
end

target 'OUASUITests' do
    import_pods
end

